server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
spring:
  profiles:
    active: dev
  application:
    name: service-user
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc-news-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123
  data:
    mongodb:
      uri: mongodb://root:root@192.168.98.103:27017
      database: imooc-news
#    database: 0 # Redis数据库索引（默认为0）
#    port: 6379
#    password: 123456
#    timeout: 0 # 连接超时时间（毫秒）
#      host:
#      jedis:
#        pool:
#          max-idle:
