server:
  port: 7004
  max-http-header-size: 500KB

spring:
  redis:
    host: 192.168.98.100
    port: 6379
    password: 123456
    timeout: 30s
    jedis:
      pool:
        max-idle: 20
        min-idle: 10
        max-active: 200
        max-wait: -1ms

