server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
spring:
  profiles:
    active: dev
  application:
    name: service-files
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 9912000 #请求文件大小限制为500kb,以b为单位
      max-request-size: 9912000
  data:
    mongodb:
      database: imooc-news
      uri: mongodb://root:ab215687DA.@192.168.98.103:27017
#    database: 0 # Redis数据库索引（默认为0）
#    port: 6379
#    password: 123456
#    timeout: 0 # 连接超时时间（毫秒）
#      host:
#      jedis:
#        pool:
#          max-idle:

#fdfs配置
fdfs:
  connect-timeout: 30
  so-timeout: 30
  tracker-list: 192.168.98.102:22122